### ISSUE TITLE
Archetype overrides are validated but not honored

### ISSUE THREAD

**Issue by rdbartram** [Azure/terraform-provider-alz#173]
If i have a file in my custom lib 

corp.alz_archetype_override.yml
```yaml
name: "corp_override"
base_archetype: "corp"
policy_assignments_to_add:
  - "Deny-MgmtPorts-Internet"
policy_assignments_to_remove:
  - "Deny-HybridNetworking"
policy_definitions_to_add: []
policy_definitions_to_remove: []
policy_set_definitions_to_add: []
policy_set_definitions_to_remove: []
role_definitions_to_add: []
role_definitions_to_remove: []
```

The add a remove assignment will just be completely ignored
